Fix multi gpu not on separate lines
kiedtl/winfetch pull request #127
Opened 2022-02-04 15:46 UTC by HO-COOH

This is how `neofetch` showing multiple gpus
![image](https://user-images.githubusercontent.com/42881734/152558662-074e53fa-f410-49fa-a0a0-689d45ae3642.png)

This is how `winfetch` showing multiple gpus before this change
![image](https://user-images.githubusercontent.com/42881734/152558794-fa4e7c27-8d36-48ce-a0b8-f51a5be121af.png)

This is after this change
![image](https://user-images.githubusercontent.com/42881734/152558873-4bda9f58-21b1-411a-ae78-25feb7870b51.png)

2022-02-04 16:17 UTC, rashil2000 commented
Please do not make formatting changes in the PR. Only change the working code.

2022-02-04 16:42 UTC, HO-COOH commented
Okay. Didn't notice vscode reformat something.

2022-02-05 17:55 UTC, rashil2000 commented
Winfetch already supports multiline output. You should modify the `info_gpu` function to handle multiple GPUs better. See the `info_colorbar` to see how it's done.

What is the output of `(Get-CimInstance -ClassName Win32_VideoController -Property Name).Name` on your system?

2022-02-18 15:04 UTC, rashil2000 commented
There are still some whitespace changes in the bottom part, kindly revert them

2022-02-18 19:50 UTC, rashil2000 requested changes

2022-02-18 19:50 UTC, rashil2000 commented on winfetch.ps1
> +#
```suggestion
#

```

2022-02-18 19:50 UTC, rashil2000 commented on winfetch.ps1
> +    foreach ($gpu in Get-CimInstance -ClassName Win32_VideoController -CimSession $cimSession) {
```suggestion
    foreach ($gpu in Get-CimInstance -ClassName Win32_VideoController -Property Name -CimSession $cimSession) {
```

2022-02-18 19:50 UTC, rashil2000 commented on winfetch.ps1
>          title   = "GPU"
```suggestion
            title   = "GPU"
```

2022-02-19 13:23 UTC, merged